global:
  security:
    allowInsecureImages: true

ingress:
  enabled: true
  className: nginx
  host: bank-api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/enable-underscores-in-headers: "true"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-User-Info"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
  observability:
    grafanaHost: grafana.bank-api
    prometheusHost: prometheus.bank-api
    zipkinHost: zipkin.bank-api
    kibanaHost: kibana.bank-api

postgresql:
  image:
    registry: docker.io
    repository: library/postgres
    tag: 15
  auth:
    username: bank_admin
    password: bank_admin
    database: bank_db
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "hostpath"
    service:
      type: NodePort
      ports:
        postgresql: 5432
      nodePorts:
        postgresql: "30432"
    initdb:
      scripts:
        init.sql: |
          CREATE SCHEMA IF NOT EXISTS keycloak;
          CREATE SCHEMA IF NOT EXISTS accounts;
kafka:
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
  controller:
    replicaCount: 1
    persistence:
      enabled: true
      size: 4Gi
      storageClass: "hostpath"
    overrideConfiguration:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  broker:
    replicaCount: 0
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
accounts:
  image:
    tag: "1.0.0"
  service:
    port: 8081
  configMap:
    enabled: true
    env:
      KEYCLOAK_CLIENT_ID: accounts-service
      KEYCLOAK_ISSUER_URI: http://host.docker.internal:8080/realms/bank-app
      KEYCLOAK_TOKEN_URI: http://host.docker.internal:8080/realms/bank-app/protocol/openid-connect/token
      APP_PORT: "8081"
      ACCOUNT_DB_URL: jdbc:postgresql://bank-app-postgresql:5432/bank_db?currentSchema=accounts
      ACCOUNT_USERNAME: bank_admin
      BANK_API_URL: http://bank-api
      KAFKA_SERVERS: bank-app-kafka:9092
      ZIPKIN_ENDPOINT: http://bank-app-zipkin:9411/api/v2/spans
      LOGSTASH_HOST: bank-app-logstash
      LOGSTASH_PORT: "5000"
  serviceMonitor:
    enabled: true
  secret:
    enabled: true
    env:
      KEYCLOAK_CLIENT_SECRET: z4YSPCjeXtZWb5qkwaL0YOrRGs4TP2Go

cash:
  image:
    tag: "1.0.0"
  service:
    port: 8082
  configMap:
    enabled: true
    env:
      KEYCLOAK_CLIENT_ID: cash-service
      KEYCLOAK_ISSUER_URI: http://host.docker.internal:8080/realms/bank-app
      KEYCLOAK_TOKEN_URI: http://host.docker.internal:8080/realms/bank-app/protocol/openid-connect/token
      APP_PORT: "8082"
      BANK_API_URL: http://bank-api
      KAFKA_SERVERS: bank-app-kafka:9092
      ZIPKIN_ENDPOINT: http://bank-app-zipkin:9411/api/v2/spans
      LOGSTASH_HOST: bank-app-logstash
      LOGSTASH_PORT: "5000"
  serviceMonitor:
    enabled: true
  secret:
    enabled: true
    env:
      KEYCLOAK_CLIENT_SECRET: Op9oxqitQbCeLm3sV7OykkjkNo8CmKbs

transfer:
  image:
    tag: "1.0.0"
  service:
    port: 8085
  configMap:
    enabled: true
    env:
      KEYCLOAK_CLIENT_ID: transfer-service
      KEYCLOAK_ISSUER_URI: http://host.docker.internal:8080/realms/bank-app
      KEYCLOAK_TOKEN_URI: http://host.docker.internal:8080/realms/bank-app/protocol/openid-connect/token
      APP_PORT: "8085"
      BANK_API_URL: http://bank-api
      KAFKA_SERVERS: bank-app-kafka:9092
      ZIPKIN_ENDPOINT: http://bank-app-zipkin:9411/api/v2/spans
      LOGSTASH_HOST: bank-app-logstash
      LOGSTASH_PORT: "5000"
  serviceMonitor:
    enabled: true
  secret:
    enabled: true
    env:
      KEYCLOAK_CLIENT_SECRET: utcIlwVUDL4ExfP0VUG6t0HKDYhGev8P

notification:
  image:
    tag: "1.0.0"
  service:
    port: 8084
  configMap:
    enabled: true
    env:
      KEYCLOAK_ISSUER_URI: http://host.docker.internal:8080/realms/bank-app
      KAFKA_SERVERS: bank-app-kafka:9092
      ZIPKIN_ENDPOINT: http://bank-app-zipkin:9411/api/v2/spans
      LOGSTASH_HOST: bank-app-logstash
      LOGSTASH_PORT: "5000"
  serviceMonitor:
    enabled: true
  secret:
    enabled: false

kube-prometheus-stack:
  nodeExporter:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      retention: 1d
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1024Mi
  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  grafana:
    adminPassword: admin
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false

elasticsearch:
  replicaCount: 1
  esJavaOpts: "-Xms512m -Xmx512m"
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1536Mi
  persistence:
    enabled: true
    size: 4Gi
    storageClass: "hostpath"


logstash:
  logstashJavaOpts: "-Xmx512m -Xms512m"
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 768Mi
