services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:30432/bank_db
      KC_DB_USERNAME: bank_admin
      KC_DB_PASSWORD: bank_admin
#      KC_DB_SCHEMA: keycloak
    volumes:
      - ./common/keycloak/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
