apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  bank-app-realm.json: |
{{ .Files.Get "files/keycloak/import/bank-app-realm.json" | indent 4 }}
  bank-app-users-0.json: |
{{ .Files.Get "files/keycloak/import/bank-app-users-0.json" | indent 4 }}