apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.allLabels" . | nindent 4 }}
data:
  {{- include "keycloak.envConfigData" . | nindent 2 }}
