spring:
  profiles:
    active: prod
  application:
    name: transfer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://host.docker.internal:8080/realms/bank-app}
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:transfer-service}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:utcIlwVUDL4ExfP0VUG6t0HKDYhGev8P}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://host.docker.internal:8080/realms/bank-app}
custom:
  baseUrl:
    api-gateway: ${BANK_API_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: ${APP_PORT:8085}
