spring:
  profiles:
    active: prod
  application:
    name: transfer
  config:
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: transfer
      config:
        watch:
          delay: 3000
          enabled: true
          wait-time: 5
        enabled: true
        defaultContext: application
        data-key: data
        format: yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8085
