spring:
  application:
    name: front
  config:
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: front
      config:
        enabled: true
        watch:
          delay: 3000
          enabled: true
          wait-time: 5
        defaultContext: application
        data-key: data
        format: yaml
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always

#custom:
#  baseUrl:
#    accounts: ${ACCOUNT_BASE_URL:http://accounts}
