spring:
  application:
    name: front
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: front
      config:
        enabled: false
        prefix: config
        defaultContext: application
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

custom:
  baseUrl:
    account: ${ACCOUNT_BASE_URL:http://localhost:8081}
#    account: ${ACCOUNT_BASE_URL:http://account:8081}
