spring:
  profiles:
    active: prod
  application:
    name: notification
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    consumer:
      group-id: bank-app-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: ru.yandex.practicum.notification.model.LogEntity
        spring.json.trusted.packages: ru.yandex.practicum.notification.model

custom:
  kafka:
    notification-topic: ${BANK_APP_NOTIFICATION_TOPIC:bank-app-notification}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: ${APP_PORT:8084}
