spring:
  application:
    name: notification
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  ${KEYCLOAK_ISSUER_URI} #http://host.docker.internal:8080/realms/bank-app

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: ${APP_PORT:8084}
