{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.fullname" . }}-secret
  labels:
    {{- include "notification.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.env }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}