{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
      {{- with .Values.serviceMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "notification.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path | default "/actuator/prometheus" }}
      interval: {{ .Values.serviceMonitor.interval | default "15s" }}
{{- end }}
