replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: "8.5.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5601

elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1024Mi

readinessProbe:
  initialDelaySeconds: 30
  failureThreshold: 15
  httpGet:
    path: /api/status
    port: http
livenessProbe:
  initialDelaySeconds: 30
  failureThreshold: 15
  httpGet:
    path: /api/status
    port: http
